name: editing_software
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_quill: ^8.6.3
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  go_router: ^12.1.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
